language: node_js

node_js:
  - 0.10

services: mongodb

before_install:
- curl $KEY_TOKEN > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa

after_success:
  #- if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
  - curl $KEY_TOKEN > ./deploy_key
  - chmod 600 ./deploy_key
  - eval "$(ssh-agent)"
  - ssh-add ./deploy_key
  - git remote add deploy dokku@pi.campinhos.pt:server
  - git push deploy
  - echo "Huge Succcess";
  - fi

notifications:
  slack: pifct:t7VCTopo5DXpAz7XIzG8yuDm

env:
  global:
    secure: TmU4AAGXnOtn5LBnsZGVtA5zh+9oB1xW1ujZRTy8a4mNwGNaLTRQYBl6eljbm5dz9TagKZ0wlSUHS138+OqGvOnqBg+HQU5ou8XArzBWPj+kIVdV8bZ4G0mwoK+CJw6dgG96lBwFso/artOo93rJRJa9In4zvoCgl0493toDtAE=
