language: node_js

node_js:
  - 0.10

services: mongodb

before_install:
  - curl $KEY_TOKEN > ~/.ssh/id_rsa
  - curl $KEY_TOKENP > ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/id_rsa*
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then
  - git remote add deploy dokku@pi.campinhos.pt:server
  - git push deploy master
  - fi

notifications:
  slack: pifct:t7VCTopo5DXpAz7XIzG8yuDm

env:
  global:
  - secure: LD0/dwfuSdPhsIolBti8DOesHb4hMFWCgaTGbHSffYN+QfWHNbFmn44AKzrVUa50JjBn25CHWrEaU9vdLxNy08oM6sYbUIq+1V4f8fnKMdWMnZeyZkzDsG/CkS4irXLEBFBBMQ64W6oottqR1JH9B6K+GfOi6h96Ldogm+MPCjk=
  - secure: PofhlULQvQXXElq6Np2BtgopdEfRGbdpGV3eED47mXaFghhr6mgwbU5mgJ9goSmR5poCwPFomAsYKZZWEgESNICQ8s/jK0IR8jRqNpyMMnpHGLX/8LcJZUwUr0Epwqmh5BiLmbbeTwjFM3E46Ya9tg/iWLVe6fOAHFM1Hc0ZhVM=
