language: node_js

node_js:
  - 0.10

services: mongodb

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then echo "deploy"; fi

notifications:
  slack: pifct:t7VCTopo5DXpAz7XIzG8yuDm
